### ISSUE TITLE
Fix recipe for kafka-bundle

### ISSUE THREAD

**Issue by Dyachenko** [symfony-bundles/kafka-bundle#13]
There was unrecognized option "topics" under "sb_kafka" in the recipe file sb_kafka.yaml .

This was fixes in PR
https://github.com/symfony/recipes-contrib/pull/868
Could you please check and approve if it's ok.

**Comment by khaperets** [comment]
Yevgeniy, thanks for your activity. Code Review +. Members of symfony/recipes-contrib will merge your MR.
